#!/bin/bash

set -e
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

# Read inputs
$destination=$1
payload=$(mktemp kubectl-resource-request.XXXXXX)
cat > $payload <&0

cd $destination
echo "pwd: $(pwd)"

echo '{ "ref" : "none" }' >&3